service: comms-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  profile: comms-service-user
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendRawEmail"
      Resource: "*"

functions:
  email:
    handler: handler.email
    events:
      - http:
          path: email
          method: post
          cors: true
